name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore and Build
        run: dotnet build --configuration Release

      - name: Pack NuGet
        run: dotnet pack Primes.Lib/Primes.Lib.csproj --configuration Release -p:PackageVersion=2022074263 --output ./nuget

      - name: Publish NuGet to GitHub Packages
        run: dotnet nuget push ./nuget/*.nupkg --source "https://nuget.pkg.github.com/LuzkalidGM/" --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
